### ISSUE TITLE
Automatically create new versions based on @types/react-native

### ISSUE THREAD

**Issue by kristerkari** [kristerkari/react-native-types-for-css-modules#1]
Manually updating new versions to this repo is hard and unnecessary.

There should be a script to automate all this:

1) get the version that matches both package.json's version and a git tag, e.g. 0.52.4
2) list `@types/react-native` versions from npm.
3) filter out versions that are older than the current version
4) download the version that is the next one from the current one.
5) Search the files for pattern `style?: StyleProp<...>;` and add a new line after with `className?: StyleProp<...>;`.
6) bump package.json version, commit, create a new tag, push to origin master.
7) Repeat for the next versions.

It would be good to have some kind of hook that triggers when a new version of `@types/react-native` is published to npm.

**Comment by kristerkari** [comment]
Done, `update_versions.rb`.

**Comment by c-harding** [comment]
Is this done on a hook? If not, it could be set up to run daily on Travis.

**Comment by kristerkari** [comment]
> Is this done on a hook? If not, it could be set up to run daily on Travis.

I have been doing it manually, but it should of course be automated. Does Travis support running tasks on daily basis? Let me know if you have a good idea of how to automate updating the types.

**Comment by c-harding** [comment]
Yes, Travis allows [cron jobs](https://docs.travis-ci.com/user/cron-jobs/). Although I've never tried, I would assume it's possible to push commits and tags back to github with it, with an API key.

**Comment by c-harding** [comment]
Aha, this Gist seems to show how to: https://gist.github.com/willprice/e07efd73fb7f13f917ea

**Comment by kristerkari** [comment]
Nice, thanks for the links! I need to check them out
